name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Prepare
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm git meson glslang libcap wlroots \
            sdl2 vulkan-headers libx11 libxcomposite libxrender libxres \
            libxtst libxkbcommon libdrm libinput wayland-protocols \
            xorg-xwayland
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          meson build/
          ninja -C build/
